### ISSUE TITLE
encoder decoder abstraction layer

### ISSUE THREAD

**Issue by BenjaminBenetti** [CanadianCommander/csc461_project#5]
do this

**Comment by lithiumtoast** [comment]
https://github.com/strukturag/libde265/wiki/Decoder-API-Tutorial

**Comment by lithiumtoast** [comment]
https://github.com/cisco/openh264/wiki

**Comment by lithiumtoast** [comment]
JPEG 2000: 
https://github.com/uclouvain/openjpeg

**Comment by BenjaminBenetti** [comment]
done in #7
